name = "HTDP"
version = "0.1.0"
defaultTargets = ["htdp"]

[[lean_lib]]
name = "HTDP"

[[lean_exe]]
name = "htdp"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "master"
